### PR TITLE
Cran comments

### PR DESCRIPTION
**Pull request by Baltmann01**
Added the missing CRAN Review Comment boxes. Hope I didn't miss any...

### CODE REVIEW

**Comment by llrs** [comment]
I didn't check all but what I think they lack too is the error, warning or note that trigger those. This seems like a good PR to add them for all the receipts.

**Review by jasdumas — APPROVED** [review]
👏 thank you for adding these in!

**Comment by jasdumas** [comment]
> I didn't check all but what I think they lack too is the error, warning or note that trigger those. This seems like a good PR to add them for all the receipts.

Thats a good note for those that are applicable. Many of the issues are not caught in the R CMD check.

**Comment by Baltmann01** [comment]
> I didn't check all but what I think they lack too is the error, warning or note that trigger those. This seems like a good PR to add them for all the receipts.

As @jasdumas already said, most of them are not checked automatically but rather manually  and therefore don't have error messages. I think for the automatically checked issues, we added NOTEs and ERRORs already but I will double check again.

**Pull request merged**
