### PR TITLE
small paragraph about emailing the cran team

### PR DESCRIPTION
**Pull request by jasdumas**
Adding a small paragraph in the general section to direct maintainers to cc cran
Board ticket: https://github.com/orgs/r-devel/projects/3/views/1?pane=issue&itemId=81474290

### CODE REVIEW

**Review by llrs — CHANGES_REQUESTED** [review]
It would be nice to remind users to avoid any html formatted email, and to use only, and exclusively text email (Check with the [CRAN policy](https://cran.r-project.org/web/packages/policies.html)). 
Lately, it has been more frequent that maintainers get a quick and blunt response when they don't do that answering to CRAN volunteers. This is a very bad experience for maintainers and it has been affecting the community and its relation with CRAN for some time.

**Comment by jasdumas** [comment]
> It would be nice to remind users to avoid any html formatted email, and to use only, and exclusively text email (Check with the [CRAN policy](https://cran.r-project.org/web/packages/policies.html)). 
> 
> Lately, it has been more frequent that maintainers get a quick and blunt response when they don't do that answering to CRAN volunteers. This is a very bad experience for maintainers and it has been affecting the community and its relation with CRAN for some time. 

Do you have an example of this that I can point to? I can include it as a callout section

**Comment by llrs** [comment]
About a "personal" email from one of the CRAN maintainers calling things to maintainers for not following this rule? They are usually taken down at the request of some veteran members. Can you, @jasdumas, guarantee that if I post one here it won't get taken down or I won't receive complains for it? 

Once I get that assurance I'll ask a couple of maintainer I know or search on an archive and post it here.

**Review by Baltmann01 — COMMENTED** [review]
Looks good!

**Pull request merged**
